### ISSUE TITLE
License for this repository 

### ISSUE THREAD

**Issue by fcooper8472** [mathii/pyEigenstrat#1]
Hi @mathii,

I see there is no license file in this repository.

This, unfortunately, means a colleague of mine is unable to reproduce this code with his current work.  This may be as you intended - but - if you had intended to allow others to use this code, please could you consider adding a license of your choice to the repository?

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

https://choosealicense.com/

Many thanks.

**Comment by mathii** [comment]
Added
